SacramentPlanner/Models/Meeting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SacramentPlanner.Models
{
    public class Meeting
    {
        public int MeetingId { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public DateTime MeetingDate { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$")]
        [Required]
        public string Conducting { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$")]
        [Display(Name = "Opening Prayer")]
        [Required]
        public string OpenPray { get; set; }

        [Range(1, 341)]
        [Display(Name = "Opening Hymn")]
        public string OpenHymn { get; set; }

        [Range(1, 341)]
        [Display(Name = "Sacrament Hymn")]
        public string SacramentHymn { get; set; }


        [Range(1, 341)]
        [Display(Name = "Intermediate Hymn")]
        public string IntermediateHymn { get; set; }

        [Range(1, 341)]
        [Display(Name = "Closing Hymn")]
        public string ClosingHymn { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$")]
        [Display(Name = "Closing Prayer")]
        [Required]
        public string ClosingPray { get; set; }

        
        /* navigation properties */
        public ICollection<Speaker> Speakers { get; set; }

    }
}

SacramentPlanner/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SacramentPlanner.Data;
using SacramentPlanner.Models;

namespace SacramentPlanner.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly MeetingContext _context;

        public MeetingsController(MeetingContext context)
        {
            _context = context;
        }

        // GET: Meetings
        public async Task<IActionResult> Index(string searchString)
        {
            var meeting = from s in _context.Meetings select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                meeting = meeting.Where(s => s.Conducting.Contains(searchString));
            }

            foreach (var s in meeting)
            {
                s.Speakers = _context.Speakers.Where(x => x.Meeting.MeetingId == s.MeetingId).ToList();
            }
            return View(await meeting.ToListAsync());
        }

        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .FirstOrDefaultAsync(m => m.MeetingId == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // GET: Meetings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Meetings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MeetingId,MeetingDate,Conducting,OpenPray,OpenHymn,SacramentHymn,IntermediateHymn,ClosingHymn,ClosingPray")] Meeting meeting)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meeting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meeting);
        }

        // GET: Meetings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings.FindAsync(id);
            if (meeting == null)
            {
                return NotFound();
            }
            return View(meeting);
        }

        // POST: Meetings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MeetingId,MeetingDate,Conducting,OpenPray,OpenHymn,SacramentHymn,IntermediateHymn,ClosingHymn,ClosingPray")] Meeting meeting)
        {
            if (id != meeting.MeetingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meeting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingExists(meeting.MeetingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meeting);
        }

        // GET: Meetings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .FirstOrDefaultAsync(m => m.MeetingId == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // POST: Meetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meeting = await _context.Meetings.FindAsync(id);
            _context.Meetings.Remove(meeting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeetingExists(int id)
        {
            return _context.Meetings.Any(e => e.MeetingId == id);
        }
    }
}

SacramentPlanner/Views/Meetings/Create.cshtml
@model SacramentPlanner.Models.Meeting

@{
    ViewData["Title"] = "Create New Meeting";
}

<h1>Create</h1>

<h4>Meeting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conducting" class="control-label"></label>
                <input asp-for="Conducting" class="form-control" />
                <span asp-validation-for="Conducting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpenPray" class="control-label"></label>
                <input asp-for="OpenPray" class="form-control" />
                <span asp-validation-for="OpenPray" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpenHymn" class="control-label"></label>
                <input asp-for="OpenHymn" class="form-control" min="1" max="341"/>
                <span asp-validation-for="OpenHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" min="1" max="341"/>
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntermediateHymn" class="control-label"></label>
                <input asp-for="IntermediateHymn" class="form-control" min="1" max="341"/>
                <span asp-validation-for="IntermediateHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" min="1" max="341" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingPray" class="control-label"></label>
                <input asp-for="ClosingPray" class="form-control" />
                <span asp-validation-for="ClosingPray" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentPlanner/Views/Meetings/Delete.cshtml
@model SacramentPlanner.Models.Meeting

@{
    ViewData["Title"] = "Delete Scheduled Meeting";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Conducting)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Conducting)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpenPray)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpenPray)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpenHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpenHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SacramentHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SacramentHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IntermediateHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IntermediateHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingPray)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingPray)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MeetingId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SacramentPlanner/Views/Meetings/Details.cshtml
@model SacramentPlanner.Models.Meeting

@{
    ViewData["Title"] = "Details of Meeting";
}

<h1>Details</h1>

<div>
    <h4>Meeting</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Conducting)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Conducting)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpenPray)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpenPray)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OpenHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OpenHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SacramentHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SacramentHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IntermediateHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IntermediateHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingHymn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingHymn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingPray)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClosingPray)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MeetingId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SacramentPlanner/Views/Meetings/Edit.cshtml
@model SacramentPlanner.Models.Meeting

@{
    ViewData["Title"] = "Edit Scheduled Meeting";
}

<h1>Edit</h1>

<h4>Meeting</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MeetingId" />
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conducting" class="control-label"></label>
                <input asp-for="Conducting" class="form-control" />
                <span asp-validation-for="Conducting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpenPray" class="control-label"></label>
                <input asp-for="OpenPray" class="form-control" />
                <span asp-validation-for="OpenPray" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpenHymn" class="control-label"></label>
                <input asp-for="OpenHymn" class="form-control" min="1" max="341" />
                <span asp-validation-for="OpenHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" min="1" max="341"/>
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IntermediateHymn" class="control-label"></label>
                <input asp-for="IntermediateHymn" class="form-control"min="1" max="341" />
                <span asp-validation-for="IntermediateHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" min="1" max="341" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClosingPray" class="control-label"></label>
                <input asp-for="ClosingPray" class="form-control" />
                <span asp-validation-for="ClosingPray" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacramentPlanner/Views/Meetings/Index.cshtml
@model IEnumerable<SacramentPlanner.Models.Meeting>

@{
    ViewData["Title"] = "Meetings List";
}

<h1>List of Scheduled Meetings</h1>
<!--<form asp-controller="Meetings" asp-action="Index">
    <p>
        Conducting: <input type="text" name="SearchString">
        <input type="submit" value="Search" class="button" />
    </p>
</form>-->
<p>
    <a asp-action="Create">Create New Meeting Plan</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <a>
                    @Html.DisplayNameFor(model => model.MeetingDate)
                </a>
            </th>
            <th style="text-align:left;">
                Details
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Speakers)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MeetingDate)
                </td>
                <td>
                    <ul>
                        <li>
                            <b> @Html.DisplayNameFor(modelItem => item.Conducting) </b>:
                            @Html.DisplayFor(modelItem => item.Conducting)
                            <ul>

                                <li>
                                    <b>
                                        @Html.DisplayNameFor(modelItem => item.OpenPray)
                                    </b>:
                                    @Html.DisplayFor(modelItem => item.OpenPray)
                                    <ul>

                                        <li>
                                            <b>
                                                @Html.DisplayNameFor(modelItem => item.OpenHymn)
                                            </b>: #
                                            @Html.DisplayFor(modelItem => item.OpenHymn)

                                        </li>

                                        <li>
                                            <b>
                                                @Html.DisplayNameFor(modelItem => item.SacramentHymn)
                                            </b>: #
                                            @Html.DisplayFor(modelItem => item.SacramentHymn)
                                        </li>

                                        <li>
                                            <b>
                                                @Html.DisplayNameFor(modelItem => item.IntermediateHymn)
                                            </b>: #
                                            @Html.DisplayFor(modelItem => item.IntermediateHymn)
                                        </li>

                                        <li>
                                            <b>
                                                @Html.DisplayNameFor(modelItem => item.ClosingHymn)
                                            </b>: #
                                            @Html.DisplayFor(modelItem => item.ClosingHymn)
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <b>
                                        @Html.DisplayNameFor(modelItem => item.ClosingPray)
                                    </b>:
                                    @Html.DisplayFor(modelItem => item.ClosingPray)
                                </li>
                            </ul>
                        </li>
                    </ul>
                </td>
                <td>
                    <!--HERE IS WHERE THE SPEAKERS WILL LOAD where name and topic are the only fields-->
                    <ul>
                        <a href="~/Speakers/Index/@item.MeetingId">Add Speakers</a>
                        @if (item.Speakers != null)
                        {
                            @foreach (var speaker in item.Speakers)
                            {
                                <li>
                                    <b>Name: </b>@Html.DisplayFor(modelItem => speaker.Name)<ul>
                                        <li><b>Topic:</b> @Html.DisplayFor(modelItem => speaker.Topic)</li>
                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MeetingId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.MeetingId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.MeetingId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>